[tasks.build]
dependencies = ["wasm-pack-build", "npm-install"]
watch = { ignore_pattern = "www/**/*" }

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--write-mode=overwrite"]

[tasks.wasm-pack-build]
install_crate = "wasm-pack"
command = "wasm-pack"
args = ["build"]

[tasks.npm-install]
cwd = "www"
command = "npm"
args = ["install"]

[tasks.npm-run]
cwd = "www"
command = "npm"
args = ["run", "start"]
env = { "NODE_OPTIONS" = "--openssl-legacy-provider" }

[tasks.cert]
cwd = "www"
command = "openssl" 
args = ["req","-x509","-nodes","-days","365","-newkey","rsa:2048","-keyout","localhost.key","-out","localhost.crt"]